### ISSUE TITLE
option to not send email if the SQL query returns no rows

### ISSUE THREAD

**Issue by rwickberg** [csyperski/reportout-be#1]
It would be nice if I could tell  reportout not to send the email or FTP file, or whatever, if the query the job runs returns no rows.  I want to use it to send error reports to secretaries, telling them what error exist in data they inputed that day, but if there aren't any, it'd be nice if they never got an email.

**Comment by csyperski** [comment]
Sounds like a valid use-case, we'll attempt to add this with the next update.

**Comment by rwickberg** [comment]
THANKS!
-----

Robert Wickberg
Technology Coordinator, BAMS, BUHS, and WRCC
802-451-3418

**Comment by csyperski** [comment]
Feature was merged, we'll package up and release shortly.
